controller:
  image: jenkins4eval/jenkins
  tag: latest
  healthProbes: false
  jenkinsUriPrefix: /jenkins
  installPlugins:
  - kubernetes:3600.v144b_cd192ca_a_
  - workflow-aggregator:581.v0c46fa_697ffd
  - git:4.11.3
  - configuration-as-code:1429.v09b_044a_c93de
  - docker-workflow:1.29
  - workflow-aggregator:590.v6a_d052e5a_a_b_5
  - pipeline-aws:1.43
  - gradle:1.39.4
  - github-branch-source:1677.v731f745ea_0cf
  - docker-plugin:1.2.9
  - pipeline-stage-view:2.24
  - timestamper:1.18
  ingress:
    enabled: true
    apiVersion: networking.k8s.io/v1
    path: /jenkins
  JCasC:
    defaultConfig: true
agent:
  image: pi4k8s/inbound-agent
  tag: 4.3
  podTemplates:
    spring: |
        - name: spring
          label: jenkins-spring
          serviceAccount: jenkins
          containers;
          - name: sonar
            image: sonarsource/sonar-scanner-cli:latest
            command: "/bin/sh -c"
            args: "cat"
            tryEnabled: true
          - name: docker
            image: docker:20-dind
            privileged: true
          - name: kubectl
            image: jshimko/kube-tooks-aws:3.8.1
            privileged: true
            command: "/bin/sh -c"
            args: "cat"
            ttyEnabled: true
          - name: jdk
            image: gradle:jdk11
            command: "/bin/sh -c"
            args: "cat"
            ttyEnabled: true
namespace: jenkins
persistence:
  enabled: true
  existingClaim: "jenkins-storage"